version: '3.1'
services:
  mongo:
    image: mongo
    restart: always
    container_name: mongdb
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: root
    user: root
    ports:
      - 50930:27017
    volumes:
      - ./data/db:/data/db
