version: '3.1'

services:
  nginx:
    image: daocloud.io/library/nginx:1.14
    container_name: nginx
    restart: always
    privileged: true
    environment:
      - TZ=Asia/Shanghai 
    ports:
      - 80:80
      - 443:443
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ./conf:/etc/nginx/conf.d
      - ./logs:/var/log/nginx
      - ./html:/opt/dist:ro
    networks:
      - nginx_bridge

networks:
  nginx_bridge:
    driver: bridge

